import Head from "next/head";
import { Table, Tag } from "antd";
import { useEffect, useState } from "react";

export default function Home() {
  const [columns, setColumns] = useState([]);
  const [dataSource, setDataSource] = useState([]);

  const dataType = "posts"; // comments | todos | quotes | posts | products

  useEffect(() => {
    fetch("https://dummyjson.com/" + dataType)
      .then((res) => res.json())
      .then((result) => {
        const lists = result[dataType] || [];
        const firstObject = lists[0] || {};
        const cols: any = [];

        for (const key in firstObject) {
          let render = (value: string) => {
            return <span>{value}</span>;
          };
          if (typeof firstObject[key] === "object") {
            if (Array.isArray(firstObject[key])) {
              render = (value: any) => {
                return (
                  <span>
                    {value.map((tag: any) => {
                      return <Tag>{tag}</Tag>;
                    })}
                  </span>
                );
              };
            } else {
              render = (value: string) => {
                return (
                  <span>
                    {Object.keys(value).map((key: any) => {
                      return (
                        <div>
                          {key}: {value[key]}
                        </div>
                      );
                    })}
                  </span>
                );
              };
            }
          } else {
          }
          const col = {
            title: String(key.charAt(0).toUpperCase() + key.slice(1)),
            dataIndex: key,
            render: render,
          };
          cols.push(col);
        }
        setColumns(cols);
        setDataSource(lists);
      })
      .catch((e) => {});
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Table columns={columns} dataSource={dataSource} scroll={{ y: 500 }} />
      </div>
    </>
  );
}
